#!/bin/bash

PROJECT_NAME=""

source utils/cbuilding.sh
source utils/help.sh
source utils/tools.sh

PLATFORM="linux"
FRESH=0
DEPENDENCIES=()
DEP_FRESH=0

help.description "Herramienta para compilar $PROJECT_NAME para las diferentes plataformas para las que esté configurada la compilación"
help.add_option "-h           " "Muestra esta ayuda"
help.add_option "-c           " "Limpia el directorio de compilación"
help.add_option "-d <path>    " "Ruta a una dependencia que se debe compilar previamente"
help.add_option "-f           " "Indica si se quiere recompilar las dependencias"
help.add_option "-p <platform>" "Plataforma para la que compilar el proyecto"
help.add_option "-r           " "Recompila el proyecto"

clean_folder() {
  cbuild.clean_all
}

while getopts :hp:crd:f opt; do
  case $opt in
    # General options
    h)
      help.show
      exit 0
      ;;
    p)
      PLATFORM=${OPTARG:-$PLATFORM}
      ;;
    c)
      clean_folder
      exit 0
      ;;
    r)
      FRESH=1
      ;;
    d)
      DEPENDENCIES+=(${OPTARG})
      ;;
    f)
      DEP_FRESH=1
      ;;
    # Errors
    ?)
      printf "$(color.red [!]) $(basename $0): opción incorrecta -- $OPTARG\n"
      help.show
      exit 1
      ;;
    :)
      printf "$(color.red [!]) $(basename $0): no se han proporcionado suficientes argumentos -- $OPTARG\n"
      help.show
      exit 1
      ;;
  esac
done

#------------#
# Entrypoint #
#------------#

ARGS=" -p $PLATFORM"
if [[ "$DEP_FRESH" == "1" ]]; then
  ARGS=" -r $ARGS"
fi

PROJECT_FOLDER=$(pwd)

for dep in "${DEPENDENCIES[@]}"; do
  if [[ ! -f $dep/bin/make ]]; then
      error.log "La dependencia $dep no es válida"
      exit 1
  fi

  cd $dep/bin && ./make $ARGS
  cd $PROJECT_FOLDER
done

cbuild.set_project $PROJECT_NAME

if cbuild.enter_platform $PLATFORM ; then
  if [[ "$FRESH" == "1" ]]; then
    cbuild.clean && cbuild.enter_platform $PLATFORM
  fi

  cbuild.build && cbuild.save

  cbuild.leave_platform
fi
